In [1]:
import numpy as np


In [2]:
#对二维点建立图
#k-最近邻邻建图
#A
#D
#L
#高斯和比重
#次小特征值

In [3]:
adjMatrix=np.array([[0,1,1,1,0,0],[1,0,1,1,0,0],[1,1,0,1,1,1],[1,1,1,0,1,1],[0,0,1,1,0,1],[0,0,1,1,1,0]])

In [4]:
degMatrix=np.zeros((6,6),dtype=int)

In [5]:
print(degMatrix)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [6]:
def sumrow(adjMatrix,indexi):
    sum=0
    for i in range(0,6):
        sum=sum+adjMatrix[indexi][i]
    return sum

In [7]:
for i in range(0,6):
    degMatrix[i][i]=sumrow(adjMatrix,i)

In [8]:
print(degMatrix)

[[3 0 0 0 0 0]
 [0 3 0 0 0 0]
 [0 0 5 0 0 0]
 [0 0 0 5 0 0]
 [0 0 0 0 3 0]
 [0 0 0 0 0 3]]


In [9]:
L=np.array
L=degMatrix-adjMatrix

In [10]:
#得到拉普拉斯矩阵如下:
print(L)

[[ 3 -1 -1 -1  0  0]
 [-1  3 -1 -1  0  0]
 [-1 -1  5 -1 -1 -1]
 [-1 -1 -1  5 -1 -1]
 [ 0  0 -1 -1  3 -1]
 [ 0  0 -1 -1 -1  3]]


In [11]:
L=np.matrix(L)
print(L)

[[ 3 -1 -1 -1  0  0]
 [-1  3 -1 -1  0  0]
 [-1 -1  5 -1 -1 -1]
 [-1 -1 -1  5 -1 -1]
 [ 0  0 -1 -1  3 -1]
 [ 0  0 -1 -1 -1  3]]


In [12]:
eigvalue,featurevector=np.linalg.eig(L)

In [13]:
eig=np.sort(eigvalue,axis=0)

In [14]:
print(eig)

[-4.90367336e-16  2.00000000e+00  4.00000000e+00  4.00000000e+00
  6.00000000e+00  6.00000000e+00]


In [15]:
print("由上述特征值的排序,可以得到图像的谱聚类结果")

由上述特征值的排序,可以得到图像的谱聚类结果
