In [26]:
import numpy as np
import math

In [27]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,10]])

In [28]:
print(matrix)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


In [43]:
def LU_fun(matrix):
    shape=matrix.shape
    min_n=min(shape[0],shape[1])
    L=np.zeros((min_n,min_n),dtype=np.int)
    U=np.zeros((min_n,min_n),dtype=np.int)
    for i in range(min_n):
        L[i][i]=1
    for k in range(1,min):
        if matrix[k-1][k-1]==0:
            break
        for i in range(k+1,n+1):
            L[i-1][k-1]=matrix[i-1][k-1]/matrix[k-1][k-1]
        for j in range(k,n+1):
            U[k-1][j-1]=matrix[k-1][j-1]
        for i in range(k+1,n+1):
            for j in range(k+1,n+1):
                matrix[i-1][j-1]=matrix[i-1][j-1]-L[i-1][k-1]*U[i-1][k-1]
    print(matrix)
    return 


In [44]:
LU_fun(matrix1)

TypeError: 'builtin_function_or_method' object cannot be interpreted as an integer

In [42]:
min_x=min(2,3)
A=np.zeros((min_x,min_x),dtype=np.int)
A

array([[0, 0],
       [0, 0]])