In [1]:
import numpy as np
import math

In [2]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,10]])
mat=np.array([[1,2,3],[4,5,6],[7,8,10]])
print(matrix)
print(mat)
shape=matrix.shape
min_n=min(shape[0],shape[1])
L=np.zeros((min_n,min_n),dtype=np.int)
U=np.zeros((min_n,min_n),dtype=np.int)
for i in range(min_n):
    L[i][i]=1

print(L)
print(U)




[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [3]:
for k in range(1,min_n):
    for i in range(k+1,min_n+1):
        L[i-1][k-1]=matrix[i-1][k-1]/matrix[k-1][k-1]
    for j in range(k,min_n+1):
        U[k-1][j-1]=matrix[k-1][j-1]
    for i in range(k+1,min_n+1):
        for j in range(k+1,min_n+1):
            tmp=matrix[i-1][j-1]-L[i-1][k-1]*U[i-1][k-1]
            matrix[i-1][j-1]=tmp
#Slides上的样例代码有问题.
#matrix矩阵不能得到变化            




In [4]:
print(L)
print(U)

[[1 0 0]
 [4 1 0]
 [7 1 1]]
[[1 2 3]
 [0 5 6]
 [0 0 0]]


In [5]:
def LU(A):
    n=len(A)
    ##初始化LU为零矩阵
    L=np.zeros((n,n),dtype=int)
    U=np.zeros((n,n),dtype=int)
    #用base来定义消元的基准行
    for base in range(n-1):#[0,n-2],倒数第二行是基准
        for i in range(base+1,n):#[base+1,n-1]
            L[i][base]=A[i][base]/A[base][base]
            A[i]=A[i]-L[i,base]*A[base]
    for i in range(n):#[0,n-1]
        L[i,i]=i
    U=np.array(A)#U是得到LU分解的最终结果
    print("L:")
    print(L)
    print("U:")
    print(U)

A = np.array([[1,2,3],[4,5,6],[7,8,10]])
LU(A)
    



L:
[[0 0 0]
 [4 1 0]
 [7 2 2]]
U:
[[ 1  2  3]
 [ 0 -3 -6]
 [ 0  0  1]]
