In [1]:
import numpy as np

In [3]:
matrix=np.array()
print(matrix)

[[1 0 2]
 [0 1 0]
 [2 0 1]
 [0 1 1]]


In [4]:
U,D,VT= np.linalg.svd(matrix)

In [5]:
print(U)


[[-6.95364108e-01 -9.60332228e-02  5.77350269e-01 -4.17028828e-01]
 [-3.18730871e-02 -5.23780894e-01 -5.77350269e-01 -6.25543242e-01]
 [-6.63491021e-01  4.27747671e-01 -5.77350269e-01  2.08514414e-01]
 [-2.74285486e-01 -7.30385600e-01  1.99840144e-15  6.25543242e-01]]


In [6]:
print(D)

[3.09928238 1.54740063 1.        ]


In [7]:
print(VT)

[[-0.65252078 -0.0987837  -0.75130448]
 [ 0.49079864 -0.81049889 -0.31970025]
 [-0.57735027 -0.57735027  0.57735027]]


In [8]:
pinv = np.linalg.pinv(matrix)
print(pinv)

[[-0.2173913   0.17391304  0.60869565 -0.17391304]
 [-0.26086957  0.60869565  0.13043478  0.39130435]
 [ 0.52173913 -0.2173913  -0.26086957  0.2173913 ]]


In [9]:
matrix=np.array([[1,2,1],[0,1,0],[0,0,1]])
print(matrix)
U,D,VT= np.linalg.svd(matrix)
print(U)
print(VT)
print(D)
pinv = np.linalg.pinv(matrix)
print(pinv)

[[1 2 1]
 [0 1 0]
 [0 0 1]]
[[ 0.93417236  0.          0.35682209]
 [ 0.31915138 -0.4472136  -0.83554916]
 [ 0.15957569  0.89442719 -0.41777458]]
[[ 0.35682209  0.83554916  0.41777458]
 [ 0.         -0.4472136   0.89442719]
 [ 0.93417236 -0.31915138 -0.15957569]]
[2.61803399 1.         0.38196601]
[[ 1.00000000e+00 -2.00000000e+00 -1.00000000e+00]
 [ 4.22724325e-17  1.00000000e+00  5.77345902e-17]
 [ 2.11362162e-17  2.22343897e-18  1.00000000e+00]]


In [10]:
matrix=np.array([[1,0,2],[0,1,0],[2,0,1],[0,1,1]])
print(matrix)
U,D,VT= np.linalg.svd(matrix)
print(U)
print(VT)
print(D)
pinv = np.linalg.pinv(matrix)
print(pinv)

[[1 0 2]
 [0 1 0]
 [2 0 1]
 [0 1 1]]
[[-6.95364108e-01 -9.60332228e-02  5.77350269e-01 -4.17028828e-01]
 [-3.18730871e-02 -5.23780894e-01 -5.77350269e-01 -6.25543242e-01]
 [-6.63491021e-01  4.27747671e-01 -5.77350269e-01  2.08514414e-01]
 [-2.74285486e-01 -7.30385600e-01  1.99840144e-15  6.25543242e-01]]
[[-0.65252078 -0.0987837  -0.75130448]
 [ 0.49079864 -0.81049889 -0.31970025]
 [-0.57735027 -0.57735027  0.57735027]]
[3.09928238 1.54740063 1.        ]
[[-0.2173913   0.17391304  0.60869565 -0.17391304]
 [-0.26086957  0.60869565  0.13043478  0.39130435]
 [ 0.52173913 -0.2173913  -0.26086957  0.2173913 ]]
